#############################################
homeassistant:
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: 50
  unit_system: metric
  time_zone: !secret time_zone
  name: KachTown
  allowlist_external_dirs:
    - /tmp
  customize: !include_dir_merge_named customize
  internal_url: !secret url_ssl
  external_url: !secret url_ssl

# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:
python_script:

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
http:
    use_x_forwarded_for: true
    trusted_proxies:
      - 192.168.10.0/24
      - 127.0.0.1
      - !secret external_ip
      - 172.19.0.0/16
      - 172.18.0.0/16
      - 172.17.0.0/16

# Includes files setting GLOBAL
group: !include_dir_merge_named group

automation: !include_dir_merge_list automations

climate: !include devices/climates.yaml
switch: !include_dir_merge_list devices/switches
light: !include devices/lights.yaml
lock: !include devices/locks.yaml
sensor: !include_dir_merge_list devices/sensors
binary_sensor: !include_dir_merge_list devices/binary_sensors
media_player: !include devices/media_players.yaml
cover: !include devices/cover.yaml
zone: !include zones.yaml
timer: !include devices/timers.yaml
template: !include_dir_merge_list devices/templates

frontend:
  themes: !include_dir_merge_named themes

#############################################
input_boolean: !include_dir_merge_named inputs/input_boolean
input_select: !include_dir_merge_named inputs/input_select
input_datetime: !include_dir_merge_named inputs/input_datetime
input_number: !include_dir_merge_named inputs/input_number
#############################################
scene: !include_dir_merge_list scenes
script: !include_dir_merge_named scripts

#############################################
config:
recorder:
  db_url: !secret db_url
  db_retry_wait: 30
  purge_keep_days: 30

#############################################

#############################################
# yandex_smart_home: !include devices/yandex_smart_home.yaml

#############################################
telegram_bot:
  - platform: polling
    api_key: !secret telegram_chatbot_api_key
    allowed_chat_ids:
      - -487298367 # Грачев
      - 490740136 # kach
      - -1001396494053 #Общий для интернета
      - -1001489548186 #Семейный
      - -1001246233382 # Dev
      - -334095822 # Buba

notify:
  - name: telegram_dev
    platform: telegram
    chat_id: -1001246233382
  - name: telegram_all
    platform: telegram
    chat_id: -1001396494053
  - name: telegram_kach
    platform: telegram
    chat_id: 490740136
  - name: telegram_family
    platform: telegram
    chat_id: -1001489548186
  - name: telegram_grachev
    platform: telegram
    chat_id: -487298367
  - name: telegram_buba
    platform: telegram
    chat_id: -334095822


#############################################
mqtt:
  broker: 192.168.10.5
  port: 1883
  username: !secret mqtt_user
  password: !secret mqtt_password


#############################################
hacs:
  token: !secret github_token

  #############################################
smartthinq:
  token: !secret lg_token
  region: RU
  language: ru-RU

#############################################
webostv:
  host: 192.168.10.23
  name: Kitchen TV

modbus:
  - name: "Turkov"
    type: tcp
    host: 192.168.10.19
    port: 502
    sensors:
      - name: turkov_inside_temperature
        address: 0x102
        slave: 5
        input_type: input
        unit_of_measurement: °C
        scale: 0.1
        precision: 1
      - name: turkov_filter_state
        address: 0x106
        slave: 5
        input_type: input
        unit_of_measurement: "%"
        precision: 1
      - name: turkov_outside_temperature
        address: 0x101
        slave: 5
        input_type: input
        unit_of_measurement: °C
        scale: 0.1
        precision: 1
      - name: turkov_error
        address: 0x107
        slave: 5
        input_type: input
      - name: turkov_fans_speed
        address: 0x03
        slave: 5
        input_type: holding
      - name: turkov_climate_mode
        address: 0x04
        slave: 5
        input_type: holding
    switches:
      - name: turkov_vent
        address: 0x01
        slave: 5
        write_type: holding
        verify:
            input_type: holding
            address: 0x01
            state_on: 1
            state_off: 0

fan:
  - platform: template
    fans:
      central_ventilation:
        friendly_name: "Центральная вентиляция"
        value_template: "{{ states('switch.turkov_vent') }}"
        preset_mode_template: >
          {% if is_state('sensor.turkov_climate_mode', '0') %}
            Normal
          {% elif is_state('sensor.turkov_climate_mode', '1') %}
            Heater
          {% elif is_state('sensor.turkov_climate_mode', '2') %}
            Cooling
          {% else %}
            Normal
          {% endif %}
        turn_on:
          service: switch.turn_on
          entity_id: switch.turkov_vent
        turn_off:
          service: switch.turn_off
          entity_id: switch.turkov_vent
        set_preset_mode:
          service: script.turkov_set_preset_mode
          data:
            preset_mode: "{{ preset_mode }}"
        speed_count: 6
        preset_modes:
          - 'Normal'
          - 'Heater'
          - 'Cooling'
          - 'Away'

# camera:
#   - platform: ffmpeg
#     # still_image_url: http://172.16.55.107:8899/
#     input: "rtsp://172.16.55.107:554/user=user_password=1234_channel=1_stream=0.sdp?real_stream"
#     # extra_arguments: "-q:v 3"
#     name: Magistre_cam
#     # username: user
#     # password: 1234
#     # verify_ssl: false
#     # rtsp_transport: tcp
