#############################################
homeassistant:
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: 50
  unit_system: metric
  time_zone: !secret time_zone
  name: KachTown
  allowlist_external_dirs:
    - /tmp
  customize: !include_dir_merge_named customize
  internal_url: !secret url_ssl
  external_url: !secret url_ssl

# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:
python_script:

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
http:
    use_x_forwarded_for: true
    trusted_proxies:
      - 192.168.10.0/24
      - 127.0.0.1
      - !secret external_ip
      - 172.19.0.0/16
      - 172.18.0.0/16
      - 172.17.0.0/16

# Includes files setting GLOBAL
group: !include_dir_merge_named group/

automation: !include_dir_merge_list automations/

climate: !include devices/climates.yaml
light: !include devices/lights.yaml
lock: !include devices/locks.yaml
sensor: !include devices/sensors.yaml
binary_sensor: !include devices/binary_sensors.yaml
media_player: !include devices/media_players.yaml
cover: !include devices/cover.yaml
zone: !include zones.yaml
timer: !include devices/timers.yaml

frontend:
  themes: !include_dir_merge_named themes

#############################################
input_boolean: !include_dir_merge_named inputs/input_boolean/
input_select: !include_dir_merge_named inputs/input_select/
input_datetime: !include_dir_merge_named inputs/input_datetime/
input_number: !include_dir_merge_named inputs/input_number/
#############################################
scene: !include_dir_merge_list scenes/
script: !include_dir_merge_named scripts/

#############################################
config:
recorder:
  db_url: !secret db_url

#############################################

#############################################
yandex_smart_home: !include devices/yandex_smart_home.yaml

yandex_station:
  username: !secret yandex_username
  password: !secret yandex_password

#############################################
telegram_bot:
  - platform: broadcast
    api_key: !secret telegram_chatbot_api_key 
    allowed_chat_ids:
      - -487298367 # Грачев
      - 490740136 # kach
      - -1001396494053 #Общий для интернета
      - -1001489548186 #Семейный
      - -1001246233382 # Dev
notify:
  - name: telegram_dev
    platform: telegram
    chat_id: -1001246233382
  - name: telegram_all
    platform: telegram
    chat_id: -1001396494053
  - name: telegram_kach
    platform: telegram
    chat_id: 490740136
  - name: telegram_family
    platform: telegram
    chat_id: -1001489548186
  - name: telegram_grachev
    platform: telegram
    chat_id: -487298367

#############################################
plex:
   host: !secret host
   port: 32400
   token: !secret plex_server_token

#############################################
transmission:
  host: !secret transmission_host

#############################################
zwave:
  usb_path: /dev/ttyACM0
  device_config: !include zwave/device_config.yaml
  polling_interval: 3600000
  network_key: !secret zwave_network_key

#############################################
mqtt:
  broker: 192.168.10.5
  port: 1883
  username: !secret mqtt_user
  password: !secret mqtt_password


#############################################
hacs:
  token: !secret github_token

  #############################################
smartthinq:
  token: !secret lg_token
  region: RU
  language: ru-RU

#############################################
webostv:
  host: 192.168.10.23
  name: Kitchen TV