- alias: kitchen_presence_on
  trigger:
    - platform: state
      entity_id: binary_sensor.kitchen_motion
      to: 'on'
    - platform: state
      entity_id: binary_sensor.kitchen_sofa_motion
      to: 'on'  
  action:
    - service: timer.start
      entity_id: timer.kitchen_lights_off
    - service: mqtt.publish
      data:
        topic: "custom/binary_sensor/kitchen_presence_detector/status"
        payload: "ON"
  
- alias: "garage_presence_off"
  trigger: 
    - platform: event
      event_type: timer.finished
      event_data:
        entity_id: timer.kitchen_lights_off
  action: 
    choose:
      - conditions: "{{ is_state('binary_sensor.kitchen_sofa_motion', 'on') or 
                        is_state('binary_sensor.kitchen_motion', 'on') }}"
        sequence:
          - service: timer.start
            entity_id: timer.kitchen_lights_off
    default:  
      - service: mqtt.publish
        data:
          topic: "custom/binary_sensor/kitchen_presence_detector/status"
          payload_template: "OFF"