- alias: kitchen_night_sleep_mode_on
  trigger:
    platform: state
    entity_id: sensor.kitchen_active_mode
    to: 'sleep'
  action:
    - service: light.turn_off
      target:
        entity_id: light.kitchen_lights

- alias: kitchen_night_sleep_mode_auto_off
  trigger:
    - platform: template
      value_template: >
        {% if is_state('sensor.time', '7:30') and is_state('binary_sensor.workday', 'on') %}
          true
        {% elif is_state('sensor.time', '9:00') and is_state('binary_sensor.workday', 'off') %}
          true
        {% else %}
          false
        {% endif %}
  action:
    - service: switch.turn_off
      entity_id: switch.kitchen_sleep_mode