- alias: "garage and boiler lights auto on"
  trigger:
    - platform: state
      entity_id: binary_sensor.garage_presence_detector
      to: 'on'
  condition:
    - condition: state
      entity_id: group.garage_and_boiler_lights
      state: 'off'  
  action:
    - service: homeassistant.turn_on
      entity_id: group.garage_and_boiler_lights

- id: garage_and_boiler_ligth_auto_turn_off
  alias: garage_and_boiler_ligth_auto_turn_off
  trigger:
    - platform: state
      entity_id: binary_sensor.garage_presence_detector
      to: 'off'
  action:
    - service: homeassistant.turn_off
      entity_id: group.garage_and_boiler_lights