- alias: "garage light timer finished"
  trigger: 
    - platform: event
      event_type: timer.finished
      event_data:
        entity_id: timer.garage_light_off
  action: 
    - service: mqtt.publish
      data:
        topic: custom/sensor/garage_presence/status
        payload_template:  "{{ states('binary_sensor.garage_motion')|upper }}"
    - condition: state
      entity_id: binary_sensor.garage_motion
      state: "on"
    - service: timer.start
      entity_id: timer.garage_light_off  

- alias: "garage light timer started"
  trigger: 
    - platform: event
      event_type: timer.started
      event_data:
        entity_id: timer.garage_light_off
  action: 
    - service: mqtt.publish
      data:
        topic: custom/sensor/garage_presence/status
        payload: "ON"