- alias: "garage_presence_on"
  trigger: 
    - platform: event
      event_type: timer.started
      event_data:
        entity_id: timer.garage_light_off
  action: 
    - service: mqtt.publish
      data:
        topic: custom/binary_sensor/garage_presence_detector/status
        payload: "ON"

- alias: "garage_presence_off"
  trigger: 
    - platform: event
      event_type: timer.finished
      event_data:
        entity_id: timer.garage_light_off
  action:
    choose:
      - conditions: "{{ is_state('binary_sensor.garage_motion', 'on') }} "
        sequence:
          - service: timer.start
            entity_id: timer.garage_light_off
    default:    
      - service: mqtt.publish
        data:
          topic: custom/binary_sensor/garage_presence_detector/status
          payload_template: "OFF"
      