- id: open_first_gate_for_person_merzlyakovi
  alias: "Открыть ворота для Мерзляковых"
  trigger:
    - platform: state
      entity_id:
        - binary_sensor.merzlyakov_opening_gate
      to: 'on'
  action:
    - service: notify.telegram_family
      data:
        message: >-
         {% if is_state('sensor.home_mode', 'home') %}
          Мерзляковы открыли ворота
         {% else %}
          Мерзляковы пытались открыть ворота
         {% endif %}
    - condition: state
      entity_id: sensor.home_mode
      state: 'home'
    - service: switch.turn_on
      entity_id: switch.yard_gate_person

- alias: Sync data with merzlyakov HA
  trigger:
    platform: state
    entity_id:
      - sensor.turkov_outside_temperature
  action:
    service: shell_command.change_temperature_bd
    data:
      outside: "{{ trigger.to_state.state }}"
      url: !secret bd_change_temp_webhook
