- platform: template
  switches:
    kitchen_movie_mode:
      friendly_name: "Режим Кино"
      value_template: "{{ is_state('sensor.kitchen_active_mode', 'movie') }}"
      turn_on:
        service: script.change_kitchen_mode
        data:
          mode: "movie"
      turn_off:
        service: script.change_kitchen_mode
      icon_template: mdi:movie

    kitchen_sleep_mode:
      friendly_name: "Режим Ночного сна на кухне"
      value_template: "{{ is_state('sensor.kitchen_active_mode', 'sleep') }}"
      turn_on:
        service: script.change_kitchen_mode
        data:
          mode: "sleep"
      turn_off:
        service: script.change_kitchen_mode
      icon_template: mdi:power-sleep

    kitchen_day_sleep_mode:
      friendly_name: "Режим Дневного сна на кухне"
      value_template: "{{ is_state('sensor.kitchen_active_mode', 'day_sleep') }}"
      turn_on:
        service: script.change_kitchen_mode
        data:
          mode: "day_sleep"
      turn_off:
        service: script.change_kitchen_mode
      icon_template: mdi:sleep
