- alias: alarm_then_motion
  trigger:
    - platform: state
      entity_id:
        - binary_sensor.parent_room_motion_safety
        - binary_sensor.arina_room_motion_safety
        - binary_sensor.ilya_room_motion_safety
        - binary_sensor.kitchen_coridor_motion_safety
        - binary_sensor.kitchen_motion_safety
        - binary_sensor.toilet_motion_safety
        - binary_sensor.garage_motion_safety
      to: 'on'
  action:
    - service: notify.telegram_family
      data_template:
        title: "**СРАБОТАЛА СИГНАЛИЗАЦИЯ**"
        message: "{{ trigger.to_state.attributes['friendly_name'] }}"
