- alias: 'Alarm then flood detected'
  trigger:
    - platform: state
      entity_id:
        - binary_sensor.kitchen_flood_sensor
      to: 'on'
  action:
    - service: notify.telegram_family
      data_template:
        title: "**ПРОТЕЧКА**"
        message: "{{ trigger.to_state.attributes['friendly_name'] | string }}"
    - service: switch.turn_off
      entity_id: switch.boiler_room_water_supply
