- alias: Sencond floor corridor lihts turn ON
  trigger:
    - platform: sun
      event: sunset
      offset: "-01:30:00"
  action:
    - service: light.turn_on
      entity_id: light.second_floor_coridor_light

- alias: Sencond floor corridor lihts turn OFF
  trigger:
    - platform: sun
      event: sunrise
  action:
    - service: light.turn_off
      entity_id: light.second_floor_coridor_light
