- platform: template
  sensors:
    guest_toilet_door_sensor:
      friendly_name: "Датчик открытия двери в гостевом туалете"
      device_class: door
      value_template: >-
        {{ is_state('sensor.guest_toilet_door_sensor_access_control', '22') }}


- platform: workday
  name: workday
  country: RU
  workdays: [mon, tue, wed, thu, fri]
  excludes: [sat, sun, holiday]
  add_holidays:
    - '2020-02-17'
    - '2020-02-18'
    - '2020-02-19'
    - '2020-02-20'
    - '2020-02-21'

- platform: template
  sensors:
    anybody_home:
      friendly_name: 'Кто-то дома'
      entity_id:
        - sensor.processor_use
      value_template: >
        {% set ns = namespace(home=false) %}
        {% for person in states.person %}
          {% if person.state == 'home' %}
            {% set ns.home = true %}
          {% endif %}
        {% endfor %}
        {{ ns.home }}