- platform: switch
  name: garage_light
  entity_id: switch.garage_light

- platform: switch
  name: besedka_yard_ligthts
  entity_id: switch.besedka_yard_ligthts

- platform: switch
  name: yard_light_at_garage
  entity_id: switch.yard_light_at_garage

- platform: switch
  name: street_lights
  entity_id: switch.street_lights

- platform: switch
  name: boiler_room_light
  entity_id: switch.boiler_room_light

- platform: switch
  name: yard_backlight
  entity_id: switch.yard_backlight

# - platform: xiaomi_miio
#   name: 'parent_room_table_lamp'
#   host: 192.168.10.15
#   token: f1b130a37540ddeb31cbefea26a4ccad
#   model: philips.light.sread1

# - platform: xiaomi_miio
#   name: 'ilya_room_table_lamp'
#   host: 192.168.10.21
#   token: c5be8bb80d7f85fa892fa07bf5801976
#   model: philips.light.sread1

- platform: group
  name: Kitchen lights
  entities:
    - light.kitchen_light_rgb
    - light.kitchen_light_second
    - light.kitchen_light_tabletop
    - light.kitchen_corridor_light
    - light.kitchen_light