- platform: template
  lights:
    garage_light:
      friendly_name: 'Свет в гараже'
      value_template: >-
        {% if is_state('switch.garage_light', 'on') %}
          on
        {% else %}
          off
        {% endif %}
      turn_on:
        service: switch.turn_on
        data:
          entity_id: switch.garage_light
      turn_off:
        service: switch.turn_off
        data:
          entity_id: switch.garage_light

- platform: template
  lights:
    yard_light_at_garage:
      friendly_name: 'Свет перед гаражом'
      value_template: >-
        {% if is_state('switch.yard_light_at_garage', 'on') %}
          on
        {% else %}
          off
        {% endif %}
      turn_on:
        service: switch.turn_on
        data:
          entity_id: switch.yard_light_at_garage
      turn_off:
        service: switch.turn_off
        data:
          entity_id: switch.yard_light_at_garage

- platform: template
  lights:
    street_light:
      friendly_name: 'Свет на общей улице'
      value_template: >-
        {% if is_state('switch.street_lights', 'on') %}
          on
        {% else %}
          off
        {% endif %}
      turn_on:
        service: switch.turn_on
        data:
          entity_id: switch.street_lights
      turn_off:
        service: switch.turn_off
        data:
          entity_id: switch.street_lights

- platform: template
  lights:
    boiler_room_light:
      friendly_name: 'Свет в бойлерной'
      value_template: >-
        {% if is_state('switch.boiler_room_light', 'on') %}
          on
        {% else %}
          off
        {% endif %}
      turn_on:
        service: switch.turn_on
        data:
          entity_id: switch.boiler_room_light
      turn_off:
        service: switch.turn_off
        data:
          entity_id: switch.boiler_room_light

- platform: xiaomi_miio
  name: 'parent_room_table_lamp'
  host: 192.168.10.15
  token: f1b130a37540ddeb31cbefea26a4ccad
  model: philips.light.sread1

- platform: xiaomi_miio
  name: 'ilya_room_table_lamp'
  host: 192.168.10.21
  token: c5be8bb80d7f85fa892fa07bf5801976
  model: philips.light.sread1

- platform: group
  name: Kitchen lights
  entities:
    - light.kitchen_light_rgb
    - light.kitchen_light_second
    - light.kitchen_light_tabletop
    - light.kitchen_corridor_light
    - light.kitchen_light