- platform: template
  name: 'garage_gate'
  value_template: >-
    {{ is_state('switch.garage_gate', 'off') }}
  lock:
    service: switch.turn_off
    data:
      entity_id: switch.garage_gate
  unlock:
    service: switch.turn_on
    data:
      entity_id: switch.garage_gate