- platform: systemmonitor
  resources:
    - type: disk_free
      arg: /media
    - type: memory_use_percent
    - type: processor_use
    - type: load_15m

- platform: time_date
  display_options:
    - 'time'
    - 'date'

- platform: template
  sensors:
    septic_phase:
      value_template: >-
        {% if is_state('switch.septic_tank_current_phase','on') %}
        pumping
        {% else %}
        reverse
        {% endif %}
