- platform: template
  switches:
    turkov_onoff:
      value_template: "{{ is_state('sensor.turkov_onoff_state', '1') }}"
      turn_on:
        service: modbus.write_register
        data:
          hub: Turkov
          unit: 5
          address: 0x01
          value: 1
      turn_off:
        service: modbus.write_register
        data:
          hub: Turkov
          unit: 5
          address: 0x01
          value: 0