- id: alarm_motion
  alias: 'Alarm then sensor armed'
  trigger:
    - platform: state
      entity_id:
        - binary_sensor.parent_room_motion_safety
        - binary_sensor.arina_room_motion_safety
        - binary_sensor.ilya_room_motion_safety
        - binary_sensor.kitchen_coridor_motion_safety
        - binary_sensor.kitchen_motion_safety
        - binary_sensor.toilet_motion_safety
        - binary_sensor.garage_motion_safety
      to: 'on'
  action:
    - condition: template
      value_template: "{{ trigger.to_state.attributes['armed'] }}"
    - service: notify.telegram_family
      data_template:
        title: "**СРАБОТАЛА СИГНАЛИЗАЦИЯ**"
        message: "{{ trigger.to_state.attributes['friendly_name'] | string }}"

- alias: Auto alarm on by away mode
  trigger:
    - platform: state
      entity_id:
        - input_select.home_mode
      from: 'Home'
      to: 'Away'
  action:
    - service: homeassistant.turn_on
      entity_id: group.alarm_sensors
    - service: automation.turn_on
      entity_id: automation.alarm_then_sensor_armed

- alias: Auto alarm off by home mode
  trigger:
    - platform: state
      entity_id:
        - input_select.home_mode
      to: 'Home'
  action:
    - service: homeassistant.turn_off
      entity_id: group.alarm_sensors
    - service: automation.turn_off
      entity_id: automation.alarm_then_sensor_armed

- id: alarm_flood_sensors
  alias: 'Alarm then flood detected'
  trigger:
    - platform: state
      entity_id:
        - binary_sensor.kitchen_flood_sensor
      to: 'on'
  action:
    - service: notify.telegram_family
      data_template:
        title: "**ПРОТЕЧКА**"
        message: "{{ trigger.to_state.attributes['friendly_name'] | string }}"