- id: alarm_motion
  alias: 'Alarm then sensor armed'
  trigger:
    - platform: state
      entity_id:
        - binary_sensor.arina_room_motion
        - binary_sensor.guest_toilet_door_sensor
        - binary_sensor.ilya_room_motion
        - binary_sensor.kitchen_motion
        - binary_sensor.kitchen_corridor_motion
        - binary_sensor.parent_room_motion
        - binary_sensor.toilet_motion
      to: 'on'
  action:
    - condition: template
      value_template: "{{ trigger.to_state.attributes['device_armed'] }}"
    - service: notify.telegram_family
      data_template:
        title: "**СРАБОТАЛА СИГНАЛИЗАЦИЯ**"
        message: "{{ trigger.to_state.attributes['friendly_name'] | string }}"

- alias: Auto alarm on by away mode
  trigger:
    - platform: state
      entity_id:
        - input_select.home_mode
      from: 'Home'
      to: 'Away'
  action:
    - service: group.turn_on
      entity_id: group.alarm_sensors


- alias: Auto alarm off by home mode
  trigger:
    - platform: state
      entity_id:
        - input_select.home_mode
      to: 'Home'
  action:
    - service: group.turn_off
      entity_id: group.alarm_sensors