- alias: Replace Buttery
  trigger:
    platform: numeric_state
    entity_id:
      - sensor.arina_room_motion_battery_level
      - sensor.ilya_room_motion_battery_level
      - sensor.kitchen_corridor_motion_battery_level
      - sensor.kitchen_motion_battery_level
      - sensor.parent_room_motion_battery_level
      - sensor.toilet_motion_battery_level
      - sensor.guest_toilet_door_sensor_battery_level
      - sensor.kitchen_flood_sensor_battery_level
    below: 10
  action:
    - service: notify.telegram_family
      data_template:
        title: "Замените батарейку"
        message: "{{ trigger.to_state.attributes['friendly_name'] | string }}"
