- alias: turn_on_water_pump_grachev
  trigger:
    - platform: time
      at: "20:00:00"
  action:
    - service: switch.turn_on
      entity_id:
        - switch.shenzhen_neo_electronics_co_ltd_power_plug_12a_switch

- alias: water_pump_noty_off_grachev
  trigger:
    - platform: state
      entity_id: switch.shenzhen_neo_electronics_co_ltd_power_plug_12a_switch
      from: "on"
      to: "off"
  action: 
      - service: notify.telegram_grachev
        data:
          title: "Скважина Грачев"
          message: "Пошла засуха"

- alias: water_pump_noty_on_grachev
  trigger:
    - platform: state
      entity_id: switch.shenzhen_neo_electronics_co_ltd_power_plug_12a_switch
      from: "off"
      to: "on"
  action: 
      - service: notify.telegram_grachev
        data:
          title: "Скважина Грачев"
          message: "Водокачка включилась"