- alias: kitchen_presence_detect
  trigger:
    platform: state
    entity_id: binary_sensor.kitchen_motion
    to: 'on'
  action:
    - service: timer.start
      entity_id: timer.kitchen_lights_off

- alias: kitchen_light_auto_on
  trigger:
    - platform: state
      entity_id: binary_sensor.kitchen_presence_detector
      to: 'on'
    - platform: state
      entity_id: group.kitchen_manual_modes
      to: 'off'
      for:
        seconds: 2
  condition:
    - condition: state
      entity_id: group.kitchen_manual_modes
      state: 'off'
  action:
    - service: scene.turn_on
      entity_id: scene.kitchen_light_full
    - service: scene.turn_on
      entity_id: scene.kitchen_shutters_last_state

- alias: kitchen_light_auto_off
  trigger:
    platform: state
    entity_id: binary_sensor.kitchen_presence_detector
    to: 'off'
  condition:
    - condition: state
      entity_id: group.kitchen_manual_modes
      state: 'off'
  action:
    - service: scene.turn_on
      data_template:
        entity_id: >-
          {% if is_state('binary_sensor.kitchen_motion', 'off') %}
            scene.kitchen_light_off
          {% else %}
            scene.kitchen_light_full
          {% endif %}
    - condition: state
      entity_id: binary_sensor.kitchen_motion
      state: 'on'
    - service: timer.start
      entity_id: timer.kitchen_lights_off

- alias: kitchen_light_half_on
  trigger:
    platform: state
    entity_id: binary_sensor.kitchen_corridor_motion
    to: 'on'
  condition:
    - condition: state
      entity_id: group.kitchen_manual_modes
      state: 'off'
    - condition: state
      entity_id: binary_sensor.kitchen_presence_detector
      state: 'off'
  action:
    - service: scene.turn_on
      entity_id: scene.kitchen_light_half

- alias: kitchen_light_half_off
  trigger:
    platform: state
    entity_id: binary_sensor.kitchen_corridor_motion
    to: 'off'
    for: 00:03:00
  condition:
    - condition: state
      entity_id: group.kitchen_manual_modes
      state: 'off'
    - condition: state
      entity_id: binary_sensor.kitchen_presence_detector
      state: 'off'
  action:
    - service: scene.turn_on
      entity_id: scene.kitchen_light_off

- alias: kitchen_movie_mode_by_plex_on
  trigger:
    - platform: state
      entity_id: media_player.plex_kitchen_tv
      to: 'playing'
  condition:
    - condition: state
      entity_id: input_boolean.kitchen_movie_mode
      state: 'off'
  action:
    - service: input_boolean.turn_on
      entity_id: input_boolean.kitchen_movie_mode

- alias: kitchen_movie_mode_by_plex_paused
  trigger:
    - platform: state
      entity_id: media_player.plex_kitchen_tv
  condition:
    - condition: state
      entity_id: input_boolean.kitchen_movie_mode
      state: 'on'
  action:
    - service: scene.turn_on
      data_template:
        entity_id: >
          {% if is_state('media_player.plex_kitchen_tv', 'paused') %}
            scene.kitchen_light_movie_paused
          {% elif is_state('media_player.plex_kitchen_tv', 'playing') %}
            scene.kitchen_light_movie
          {% endif %}

- alias: kitchen_movie_mode_on
  trigger:
    - platform: state
      entity_id: input_boolean.kitchen_movie_mode
      to: 'on'
  action:
    - service: scene.turn_on
      entity_id: scene.kitchen_light_movie
    - condition: template
      value_template: "{{ state_attr('sun.sun', 'elevation') > -2 }}"
    - service: scene.create
      data:
        scene_id: kitchen_shutters_last_state
        snapshot_entities:
        - cover.kitchen_shutter
    - service: cover.set_cover_position
      data:
        entity_id: cover.kitchen_shutter
        position: 20

- alias: kitchen_movie_mode_off
  trigger:
    - platform: state
      entity_id: input_boolean.kitchen_movie_mode
      to: 'on'
      for: 03:00:00
    - platform: state
      entity_id: media_player.plex_kitchen_tv
      to: 'idle'
  action:
    - service: input_boolean.turn_off
      entity_id: input_boolean.kitchen_movie_mode

- alias: kitchen_day_sleep_mode_on
  trigger:
    platform: state
    entity_id: input_boolean.kitchen_day_sleep_mode
    to: 'on'
  action:
    - service: scene.turn_on
      entity_id: scene.kitchen_light_day_sleep
    - service: media_player.volume_set
      data_template:
        entity_id: media_player.nvidia_shield
        volume_level: 0.2
    - condition: template
      value_template: "{{ state_attr('sun.sun', 'elevation') > 4 }}"
    - service: scene.create
      data:
        scene_id: kitchen_shutters_last_state
        snapshot_entities:
        - cover.kitchen_shutter
    - service: cover.set_cover_position
      data:
        entity_id: cover.kitchen_shutter
        position: 40

- alias: kitchen_day_sleep_mode_off
  trigger:
    platform: state
    entity_id: input_boolean.kitchen_light_day_sleep
    to: 'on'
    for: 02:00:00
  action:
    - service: input_boolean.turn_off
      entity_id: input_boolean.kitchen_light_day_sleep
