- alias: message alarm on
  trigger:
    platform: state
    entity_id: group.alarm_sensors
    to: 'on'
  action:
    service: notify.telegram_family
    data:
      message: 'Включаю сигнализацию'

- alias: message alarm off
  trigger:
    platform: state
    entity_id: group.alarm_sensors
    to: 'off'
  action:
    service: notify.telegram_family
    data:
      message: 'Выключаю сигнализацию'