- alias: kitchen_movie_mode_by_plex_on
  trigger:
    - platform: state
      entity_id: media_player.plex_plex_for_lg_lg_65nano906na
      to: 'playing'
  condition:
    - condition: state
      entity_id: input_boolean.kitchen_movie_mode
      state: 'off'
  action:
    - service: input_boolean.turn_on
      target:
        entity_id: input_boolean.kitchen_movie_mode

- alias: kitchen_movie_mode_by_plex_paused
  trigger:
    - platform: state
      entity_id: media_player.plex_plex_for_lg_lg_65nano906na
  condition:
    - condition: state
      entity_id: input_boolean.kitchen_movie_mode
      state: 'on'
  action:
    - service: scene.turn_on
      data_template:
        entity_id: >
          {% if is_state('media_player.plex_plex_for_lg_lg_65nano906na', 'paused') %}
            scene.kitchen_light_movie_paused
          {% elif is_state('media_player.plex_plex_for_lg_lg_65nano906na', 'idle') %}
            scene.kitchen_light_movie_paused
          {% elif is_state('media_player.plex_plex_for_lg_lg_65nano906na', 'playing') %}
            scene.kitchen_light_movie
          {% endif %}

- alias: kitchen_movie_mode_on
  trigger:
    - platform: state
      entity_id: input_boolean.kitchen_movie_mode
      to: 'on'
  action:
    - service: scene.turn_on
      entity_id: scene.kitchen_light_movie
    - condition: template
      value_template: "{{ state_attr('sun.sun', 'elevation') > -2 }}"
    - service: scene.create
      data:
        scene_id: kitchen_shutters_last_state
        snapshot_entities:
        - cover.kitchen_shutter
    - service: cover.set_cover_position
      data:
        entity_id: cover.kitchen_shutter
        position: 20

- alias: kitchen_movie_mode_off
  trigger:
    - platform: state
      entity_id: input_boolean.kitchen_movie_mode
      to: 'on'
      for: '03:00:00'
    - platform: state
      entity_id: media_player.plex_plex_for_lg_lg_65nano906na
      to: 'idle'
      for:
        seconds: 45
    - platform: state
      entity_id: media_player.kitchen_tv
      to: 'off'
  action:
    - service: input_boolean.turn_off
      target:  
        entity_id: input_boolean.kitchen_movie_mode