- alias: Completed Torrent
  trigger:
    platform: event
    event_type: transmission_downloaded_torrent
  action:
    service: notify.telegram_all
    data_template:
      title: "Завершен"
      message: "{{trigger.event.data.name}}"