- alias: Wakeup to school
  trigger:
    platform: template
    value_template: >
      {% set time_string = states('sensor.date') + 'T' + states('sensor.time') + ':00+03:00'  %}
      {% set wakeup_string = states('sensor.date') + 'T' + states('input_datetime.daily_wakeup_time') + '+03:00'  %}
      {{ as_timestamp(wakeup_string) - as_timestamp(time_string) | int  == 900 }}
  condition:
    condition: state
    entity_id: binary_sensor.workday
    state: 'on'
  action:
    - service: notify.telegram_family
      data_template:
        title: "Время"
        message: "Будильник!!"
    - service: python_script.transition
      data:
        brightness: 255
        transition: 900
        entity_id: light.arina_room_light
    - service: python_script.transition
      data:
        brightness: 255
        transition: 900
        entity_id: light.ilya_room_light
