- alias: Wakeup to school
  trigger:
    platform: template
    value_template: >
      {% set time_string = states('sensor.date') + 'T' + states('sensor.time') + ':00+03:00'  %}
      {% set wakeup_string = states('sensor.date') + 'T' + states('input_datetime.daily_wakeup_time') + '+03:00'  %}
      {{ as_timestamp(wakeup_string) - as_timestamp(time_string) | int  == 900 }}
  condition:
    - condition: state
      entity_id: binary_sensor.workday
      state: 'on'
    - condition: state
      entity_id: input_boolean.enable_wakeup_alarms
      state: 'on'
  action:
    - service: notify.telegram_family
      data_template:
        title: "Время"
        message: "Будильник!!"
    - service: python_script.transition
      data:
        brightness: 255
        transition: 900
        entity_id: light.arina_room_light
    - service: python_script.transition
      data:
        brightness: 255
        transition: 900
        entity_id: light.ilya_room_light


- alias: Shutters close before sunrise
  trigger:
    - platform: sun
      event: sunrise
      offset: '-00:50:00'
  condition:
    - condition: time
      before: '07:00:00'
  action:
    service: cover.set_cover_position
    data:
      entity_id: cover.bedroom_window_covers
      position: 20


- alias: Shutters open at time
  trigger:
    platform: time
    at: '09:00:00'
  action:
    service: cover.set_cover_position
    data:
      entity_id: cover.bedroom_window_covers
      position: 100
