- id: yard_light_on
  alias: 'Включение уличного освещения'
  trigger:
    - platform: sun
      event: sunset
      offset: '00:20:00'
  action:
    - service: homeassistant.turn_on
      entity_id:
        - group.yard_night_lights
    - service: notify.telegram_kach
      data:
        message: 'ВКЛ уличное освещение'

- id: yard_light_off
  alias: 'Выключение уличного освещения'
  trigger:
    - platform: sun
      event: sunrise
      offset: '-00:20:00'
  action:
    - service: homeassistant.turn_off
      entity_id:
        - group.yard_night_lights
    - service: notify.telegram_kach
      data:
        message: 'ВЫКЛ уличное освещение'

- id: yard_septic_phase_changed
  alias: yard_septic_phase_changed
  trigger:
    - platform: state
      entity_id: sensor.septic_phase
  action:
    - service: notify.telegram_kach
      data_template:
        title: "Топас"
        message: >-
          Смена фазы сепитика на {{ states('sensor.septic_phase') }}

- alias: Open_person_gate_by_red_button
  trigger:
    platform: event
    event_type: zwave_js_value_notification
    event_data:
      device_id: aaf507008d02b4f33b8864d2c34e1576  # Red button ID
      value: KeyPressed
  action:
    service: switch.turn_on
    entity_id: switch.yard_gate_person

- alias: Open_full_gate_by_red_button
  trigger:
    platform: event
    event_type: zwave_js_value_notification
    event_data:
      device_id: aaf507008d02b4f33b8864d2c34e1576  # Red button ID
      value: KeyHeldDown
  action:
    service: switch.turn_on
    entity_id: switch.yard_gate_full

- alias: Open_garage_gate_by_red_button
  trigger:
    platform: event
    event_type: zwave_js_value_notification
    event_data:
      device_id: aaf507008d02b4f33b8864d2c34e1576  # Red button ID
      value: KeyPressed2x
  action:
    service: cover.toggle
    entity_id: cover.garage_gate
