- platform: systemmonitor
  resources:
    - type: disk_free
      arg: /media
    - type: disk_free
      arg: /config
    - type: memory_use_percent
    - type: processor_use
    - type: load_15m

- platform: time_date
  display_options:
    - 'time'
    - 'date'

- platform: template
  sensors:
    septic_phase:
      value_template: >-
        {% if states.switch.septic_tank_current_phase.state == 'on' %}
        pumping
        {% else %}
        reverse
        {% endif %}

- platform: hddtemp
  host: hddtemp
  disks:
    - /dev/sda
    - /dev/sdd
    - /dev/sdb
    - /dev/sdc

- platform: command_line
  name: CPU Temperature
  command: "cat /sys/class/thermal/thermal_zone3/temp"
  unit_of_measurement: "°C"
  value_template: "{{ value | multiply(0.001) | round(1) }}"

- platform: uptime
  name: Uptime

- platform: rest
  name: Dahovskaya_temp
  device_class: temperature
  unit_of_measurement: "°C"
  resource: !secret dah_OW_link
  value_template: '{{ value_json.main.temp|round(1, "floor") }}'
  scan_interval: 60
