- platform: systemmonitor
  resources:
    - type: disk_free
      arg: /media
    - type: disk_free
      arg: /raid
    - type: disk_free
      arg: /config
    - type: memory_use_percent
    - type: processor_use
    - type: load_15m


- platform: template
  sensors:
    septic_phase:
      value_template: >-
        {% if states.switch.septic_tank_current_phase.state == 'on' %}
        pumping
        {% else %}
        reverse
        {% endif %}

- platform: hddtemp
  host: hddtemp
  disks:
    - /dev/disk/by-id/ata-TOSHIBA_HDWD120_Z0BSK9EAS
    - /dev/disk/by-id/ata-TOSHIBA_HDWD120_Y0ONXD1AS
    - /dev/disk/by-id/ata-TOSHIBA_HDWT860_5151S79TSRXH
    - /dev/disk/by-id/ata-WDC_WD2005FBYZ-01YCBB3_WD-WCC6N3RAKC32
    - /dev/disk/by-id/ata-WDC_WD2005FBYZ-01YCBB2_WD-WMB3G1696599
    - /dev/disk/by-id/ata-ST4000VX007-2DT166_ZDH742Q1
    - /dev/disk/by-id/ata-ST4000VX007-2DT166_ZDH789TA

- platform: rest
  name: Dahovskaya_temp
  device_class: temperature
  unit_of_measurement: "°C"
  resource: !secret dah_OW_link
  value_template: '{{ value_json.main.temp|round(1, "floor") }}'
  scan_interval: 60
