- alias: Auto alarm on by away mode
  trigger:
    - platform: state
      entity_id:
        - sensor.home_mode
      to: 'away'
  action:
    - service: homeassistant.turn_on
      entity_id: group.alarm_sensors
    - service: automation.turn_on
      entity_id: automation.alarm_then_motion
