- alias: Auto alarm on by away mode
  trigger:
    - platform: state
      entity_id:
        - sensor.home_mode
      to: 'away'
  action:
    - service: script.toggle_alarm
      data:
        action: 'on'
