- alias: Auto alarm off by home mode
  trigger:
    - platform: state
      entity_id:
        - sensor.home_mode
      to: 'home'
  action:
    - service: script.toggle_alarm
      data:
        action: 'off'
