- platform: template #Датчики сигнализации
  sensors:
    parent_room_motion_safety:
      friendly_name: "Движение в спальне"
      device_class: safety
      value_template: "{{ is_state('binary_sensor.parent_room_motion', 'on') }}"
      attribute_templates:
        armed: "{{ is_state('input_boolean.parent_room_motion_arm', 'on') }}"
      icon_template: >-
        {% if is_state_attr('binary_sensor.parent_room_motion_safety', 'armed' , 'True') %}
          {% if is_state('binary_sensor.parent_room_motion_safety', 'on') %}
          mdi:shield-alert
          {% else %}
          mdi:shield-check
          {% endif %}
        {% else  %}
        mdi:shield-off-outline
        {% endif %}
    arina_room_motion_safety:
      friendly_name: "Движение в спальне Арины"
      device_class: safety
      value_template: "{{ is_state('binary_sensor.arina_room_motion', 'on') }}"
      attribute_templates:
        armed: "{{ is_state('input_boolean.arina_room_motion_arm', 'on') }}"
      icon_template: >-
        {% if is_state_attr('binary_sensor.arina_room_motion_safety', 'armed' , 'True') %}
          {% if is_state('binary_sensor.arina_room_motion_safety', 'on') %}
          mdi:shield-alert
          {% else %}
          mdi:shield-check
          {% endif %}
        {% else  %}
        mdi:shield-off-outline
        {% endif %}
    ilya_room_motion_safety:
      friendly_name: "Движение в спальне Ильи"
      device_class: safety
      value_template: "{{ is_state('binary_sensor.ilya_room_motion', 'on') }}"
      attribute_templates:
        armed: "{{ is_state('input_boolean.ilya_room_motion_arm', 'on') }}"
      icon_template: >-
        {% if is_state_attr('binary_sensor.ilya_room_motion_safety', 'armed' , 'True') %}
          {% if is_state('binary_sensor.ilya_room_motion_safety', 'on') %}
          mdi:shield-alert
          {% else %}
          mdi:shield-check
          {% endif %}
        {% else  %}
        mdi:shield-off-outline
        {% endif %}
    kitchen_coridor_motion_safety:
      friendly_name: "Движение на кухне в коридоре"
      device_class: safety
      value_template: "{{ is_state('binary_sensor.kitchen_coridor_motion', 'on') }}"
      attribute_templates:
        armed: "{{ is_state('input_boolean.kitchen_coridor_motion_arm', 'on') }}"
      icon_template: >-
        {% if is_state_attr('binary_sensor.kitchen_coridor_motion_safety', 'armed' , 'True') %}
          {% if is_state('binary_sensor.kitchen_coridor_motion_safety', 'on') %}
          mdi:shield-alert
          {% else %}
          mdi:shield-check
          {% endif %}
        {% else  %}
        mdi:shield-off-outline
        {% endif %}    
    kitchen_motion_safety:
      friendly_name: "Движение на кухне"
      device_class: safety
      value_template: "{{ is_state('binary_sensor.kitchen_motion', 'on') }}"
      attribute_templates:
        armed: "{{ is_state('input_boolean.kitchen_motion_arm', 'on') }}"
      icon_template: >-
        {% if is_state_attr('binary_sensor.kitchen_motion_safety', 'armed' , 'True') %}
          {% if is_state('binary_sensor.kitchen_motion_safety', 'on') %}
          mdi:shield-alert
          {% else %}
          mdi:shield-check
          {% endif %}
        {% else  %}
        mdi:shield-off-outline
        {% endif %}
    toilet_motion_safety:
      friendly_name: "Движение в туалете"
      device_class: safety
      value_template: "{{ is_state('binary_sensor.toilet_motion', 'on') }}"
      attribute_templates:
        armed: "{{ is_state('input_boolean.toilet_motion_arm', 'on') }}"
      icon_template: >-
        {% if is_state_attr('binary_sensor.toilet_motion_safety', 'armed' , 'True') %}
          {% if is_state('binary_sensor.toilet_motion_safety', 'on') %}
          mdi:shield-alert
          {% else %}
          mdi:shield-check
          {% endif %}
        {% else  %}
        mdi:shield-off-outline
        {% endif %}
    garage_motion_safety:
      friendly_name: "Движение в гараже"
      device_class: safety
      value_template: "{{ is_state('binary_sensor.garage_motion', 'on') }}"
      attribute_templates:
        armed: "{{ is_state('input_boolean.garage_motion_arm', 'on') }}"
      icon_template: >-
        {% if is_state_attr('binary_sensor.garage_motion_safety', 'armed' , 'True') %}
          {% if is_state('binary_sensor.garage_motion_safety', 'on') %}
          mdi:shield-alert
          {% else %}
          mdi:shield-check
          {% endif %}
        {% else  %}
        mdi:shield-off-outline
        {% endif %}