- platform: command_line
  command: 'curl --silent -XGET --max-time 3 -I https://www.automagistre.ru/|head -1|grep -q "HTTP/2 200" && (echo "ON") || (echo "OFF")'
  name: "automagistre web server"
  scan_interval: 60
  command_timeout: 4
  device_class: connectivity

- platform: command_line
  command: 'curl --silent -XGET --max-time 3 -I https://ha.astra50.ru/|head -1|grep -q "HTTP/2 200" && (echo "ON") || (echo "OFF")'
  name: "astra ha is online"
  scan_interval: 60
  command_timeout: 4
  device_class: connectivity

- platform: template
  sensors:
    anybody_home:
      friendly_name: 'Кто-то дома'
      value_template: >
        {{ is_state('person.kirill', 'home') or
           is_state('person.ilya', 'home') or
           is_state('person.valeria', 'home') }}

- platform: command_line
  command: "awk '{sum+=$2} END {print sum}' /media/raid_status"
  name: Raid disk status
  unique_id: raid_is_problem
  value_template: >
    {% if value == "0" %}
      OFF
    {% else %}
      ON
    {% endif %}
  scan_interval: 1800
  command_timeout: 4
  device_class: problem

- platform: command_line
  command: "awk '{sum+=$2} END {print sum}' /media/data_status"
  name: Media disk status
  unique_id: media_is_problem
  value_template: >
    {% if value == "0" %}
      OFF
    {% else %}
      ON
    {% endif %}
  scan_interval: 1800
  command_timeout: 1
  device_class: problem
