- platform: template
  sensors:
    anybody_home:
      friendly_name: 'Кто-то дома'
      value_template: >
        {{ is_state('person.kirill', 'home') or
           is_state('person.ilya', 'home') or
           is_state('person.valeria', 'home') }}

- platform: template
  sensors:
    guest_toilet_door_sensor:
      value_template: >-
        {{ is_state('sensor.guest_toilet_door_sensor_access_control', '22') }}