- platform: workday
  name: workday
  country: RU
  workdays: [mon, tue, wed, thu, fri]
  excludes: [sat, sun, holiday]
  add_holidays:
    - '2020-02-17'
    - '2020-02-18'
    - '2020-02-19'
    - '2020-02-20'
    - '2020-02-21'

- platform: template
  sensors:
    night_tariff:
      friendly_name: 'Ночной тариф'
      value_template: >
        {{ now() > today_at("23:10") or now() < today_at("06:55")  }}
